### ISSUE TITLE
Wrong KSPDev_Util version

### ISSUE THREAD

**Issue by 7ranceaddic7** [ihsoft/KSPDev#40] opened 2018-10-23 23:19 UTC
KSPDev_LogConsole 0.19 contains KSPDev_Utils 0.35 instead of 0.37

**Comment by ihsoft** [comment] 2018-10-23 23:27
LogConsole v0.19 is compiled against Utils 0.35. Why is it wrong? The latest LogConsole v0.21 (released in a [separate repo](https://github.com/ihsoft/KSPDev_LogConsole/releases)) uses Utils v0.37.

**Comment by 7ranceaddic7** [comment] 2018-10-24 05:39
This is the version that is installing via CKAN:
    "NAME": "KSPDev LogConsole", 
    "URL": "https://raw.githubusercontent.com/ihsoft/KSPDev/master/KSPDev_LogConsole.version", 
    "VERSION": {
        "BUILD": 6763, 
        "MAJOR": 0, 
        "MINOR": 19, 
        "PATCH": 35067

When that runs it throws exception errors calling for 0.37.

**Comment by ihsoft** [comment] 2018-10-24 07:48
Could you please paste the error here?

**Comment by 7ranceaddic7** [comment] 2018-10-24 16:23
KSP version = 1.4.5
Linux 4.18
Ubuntu 18.10

Here's the log section from the point of loading through failure.  The reason I tracked this down is because I was not getting any INFO/WARNING/ERROR logs generated.  As you can see in the pics below, 0.35 is packaged for delivery with 0.19.

[LOG 09:18:14.219] Load(Assembly): KSPDev/LogConsole/Plugins/KSPDev_LogConsole
[LOG 09:18:14.219] AssemblyLoader: Loading assembly at /home/scott/Games/KSP_vanilla/GameData/KSPDev/LogConsole/Plugins/KSPDev_LogConsole.dll
[LOG 09:18:14.219] AssemblyLoader: KSPAssembly 'KSPDev_LogConsole' V0.19.0
[LOG 09:18:14.220] Load(Assembly): KSPDev/LogConsole/Plugins/KSPDev_Utils.0.35
[LOG 09:18:14.220] AssemblyLoader: Loading assembly at /home/scott/Games/KSP_vanilla/GameData/KSPDev/LogConsole/Plugins/KSPDev_Utils.0.35.dll
[LOG 09:18:14.220] Load(Assembly): KSPDev/LogConsole/Plugins/MiniAVC
[LOG 09:18:14.220] AssemblyLoader: Loading assembly at /home/scott/Games/KSP_vanilla/GameData/KSPDev/LogConsole/Plugins/MiniAVC.dll
[LOG 09:18:14.220] Load(Assembly): Pebkac/MiniAVC
[LOG 09:18:14.220] AssemblyLoader: Loading assembly at /home/scott/Games/KSP_vanilla/GameData/Pebkac/MiniAVC.dll
[LOG 09:18:14.221] Load(Assembly): Pebkac/Plugins/PebkacLaunchEscape2
[LOG 09:18:14.221] AssemblyLoader: Loading assembly at /home/scott/Games/KSP_vanilla/GameData/Pebkac/Plugins/PebkacLaunchEscape2.dll
[LOG 09:18:14.221] Load(Assembly): TweakScale/plugins/Scale
[LOG 09:18:14.221] AssemblyLoader: Loading assembly at /home/scott/Games/KSP_vanilla/GameData/TweakScale/plugins/Scale.dll
[LOG 09:18:14.222] Load(Assembly): TweakScale/plugins/Scale_Redist
[LOG 09:18:14.222] AssemblyLoader: Loading assembly at /home/scott/Games/KSP_vanilla/GameData/TweakScale/plugins/Scale_Redist.dll
[LOG 09:18:14.223] AssemblyLoader: Loading assemblies
[LOG 09:18:14.267] ADDON BINDER: Create binding redirect: ToolbarControl, Version=0.1.6.10, Culture=neutral, PublicKeyToken=null => ToolbarControl, Version=0.1.6.16, Culture=neutral, PublicKeyToken=null
[ERR 09:18:14.268] ADDON BINDER: Cannot resolve assembly: KSPDev_Utils.0.37, Culture=neutral, PublicKeyToken=null

[ERR 09:18:14.268] ADDON BINDER: Cannot resolve assembly: KSPDev_Utils.0.37, Culture=neutral, PublicKeyToken=null

[ERR 09:18:14.270] AssemblyLoader: Exception loading 'KSPDev_LogConsole': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 

Additional information about this exception:

 System.TypeLoadException: Could not load type 'KSPDev.LogConsole.ConsoleUI' from assembly 'KSPDev_LogConsole, Version=0.19.6763.35067, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClass2' from assembly 'KSPDev_LogConsole, Version=0.19.6763.35067, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClass7' from assembly 'KSPDev_LogConsole, Version=0.19.6763.35067, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClassa' from assembly 'KSPDev_LogConsole, Version=0.19.6763.35067, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClass10' from assembly 'KSPDev_LogConsole, Version=0.19.6763.35067, Culture=neutral, PublicKeyToken=null'.


***********************************************************************************************************************
LogConsole as seen in CKAN...
![kspdev_logconsole-ckan](https://user-images.githubusercontent.com/4062616/47445219-44c57b00-d76d-11e8-80a0-fcda243b2bbe.png)
LogConsole Zip as downloaded...
![kspdev_logconsole-zipfilecontents](https://user-images.githubusercontent.com/4062616/47445223-48f19880-d76d-11e8-80c6-f71a7b7f8c03.png)
***********************************************************************************************************************P.S. I've fixed this for me by deleting the 0.35dll in the Zip and inserting the 0.37dll.  So when I install it in other games/testbeds it installs properly.

**Comment by ihsoft** [comment] 2018-10-24 17:30
Yeah, just checked `0.19` release. In spite of it was intended to use `Utils v0.35` it was actually built against `0.37`. Given there were two versions past `0.19` it doesn't make sense to fix the broken release.

Btw, you can update to the latest version. AVC will complain since you're using `KSP 1.4.5`, but other than that no problems should arise.

Thanks for the report!

**Closed as completed by ihsoft** 2018-10-24 17:30 UTC

**Comment by 7ranceaddic7** [comment] 2018-10-24 19:06
Noted.  Yeah, it throws a complaint but my vanilla install shows no log errors.
